packages:
  - websites/portfolio/common
  - websites/portfolio/editor
  - websites/portfolio/export
  - websites/recipe-website/common
  - websites/recipe-website/editor
  - websites/recipe-website/export
  - websites/resume-builder
  - packages/component-library
  - packages/next-static-image
  - packages/projects-collection
  - packages/pages-collection
  - packages/menus-collection
  - packages/content-engine
