packages:
  - websites/recipe-website/common
  - websites/recipe-website/editor
  - websites/recipe-website/export
  - packages/component-library
  - packages/next-static-image
  - packages/recipes-collection
  - packages/pages-collection
  - packages/menus-collection
  - packages/content-engine
