name: GitHub Actions Demo
run-name: Lint and test ${{ github.ref }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Check out current branch
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Lint diff from main
        run: npx lint-staged --diff main
