name: Lint
run-name: Lint ${{ github.ref }}
on: [push]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current branch
        uses: actions/checkout@v4
      - name: Fetch main
        run: git fetch origin main

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint diff from main
        run: pnpm exec lint-staged --diff origin/main
